
spring:
  jpa:
    database: default
  datasource:
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MySQL-PASSWORD}
    url: jdbc:mysql://localhost:3306/weather
server:
  port: 1234
